import { Exclude } from 'class-transformer';
import { IsUUID } from 'class-validator';
import { Column, Entity, PrimaryGeneratedColumn } from 'typeorm';

@Entity()
export abstract class Identity {
	// As this id is internal and autogenerated we exclude the field
	@Exclude()
	@PrimaryGeneratedColumn()
		id: number; // Internal identifier, automatically generated by the DB

	@IsUUID()
	@Column({
		type: 'uuid',
		nullable: false,
		update: false,
		unique: true
	})
		uuid: string; // External identifier, generated in the frontend
}
