import { IsEmail, IsString, IsStrongPassword, IsUUID } from 'class-validator';
import { Column, Entity, ManyToOne, PrimaryGeneratedColumn } from 'typeorm';
import { Role } from '../../roles/domain/Role';
import { Exclude } from 'class-transformer';
import { passwordValidationOptions } from '../users.constants';
import { ApiProperty } from '@nestjs/swagger';
import { IUser } from './IUser';

@Entity()
export class User {
	// eslint-disable-next-line @typescript-eslint/no-empty-function
	constructor(props: IUser) {}

	// As this id is internal and autogenerated we exclude the field
	@Exclude()
	@PrimaryGeneratedColumn()
		id: number; // Internal identifier, automatically generated by the DB

	@IsUUID()
	@Column({
		type: 'uuid',
		nullable: false,
		update: false,
		unique: true
	})
		uuid: string; // External identifier, generated in the frontend

	@ApiProperty()
	@IsString()
	@Column({
		nullable: false,
		update: true
	})
		name: string;

	@ApiProperty()
	@IsString()
	@Column({
		nullable: false,
		update: true
	})
		surname: string;

	@ApiProperty()
	@IsEmail()
	@Column({
		nullable: false,
		update: true
	})
		email: string;

	@Exclude({
		toPlainOnly: true
	})
	@IsStrongPassword(passwordValidationOptions)
	@Column({
		type: 'varchar',
		nullable: false,
		update: true
	})
		password: string;

	@ApiProperty()
	@ManyToOne(() => Role, (role) => role.users, {
		eager: true,
		cascade: false
	})
		role: Role;
}
